name: codecov
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: execute        
        run: |
          python ./.github/scripts/update_ee_token.py
        env:
          EE_TOKEN: ${{ secrets.EE_TOKEN }}
      - name: tests
        run: |
          tox -e py
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml

  upload-to-codecov:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2